### ISSUE TITLE
Target PDF attachments to descriptive text fields

### ISSUE THREAD

**Issue by jangari** [grezniczek/redcap_inline_full#1]
Now that PDFs attached to descriptive text fields display in a pdf reader, would you consider seeing if this module could be configured to also add a fullscreen button for those specific cases?

**Comment by jangari** [comment]
Oh wait, is this module now redundant due to the built-in fullscreen button?
<img width="783" alt="image" src="https://github.com/grezniczek/redcap_inline_full/assets/1875291/cad3ff0b-5012-4a3a-8570-03709293c6a9">

**Comment by grezniczek** [comment]
@jangari - Yes, this is obsolete now. The IN-LINE-PREVIEW is so much better. 
I probably should version-cap this module…..

**Comment by grezniczek** [comment]
The fullscreen button is independent of the preview, though and is available on the inline descrlptive pdf viewer.
